#!/bin/bash

<<comment
This is just for infotainment purpose
comment

# This is function definition

function is_loyal() {

read -p " Enter the girls name: " Shona
read -p " $1 ka pyar %" pyar

if [[ $Shona == "Anjali"  ]];
then
	echo "$1 is loyal"
elif [[ $pyar -ge 100   ]] ;
then
	echo "$1 is loyal"
else
	echo "$1 is dis;oyal"
fi
}

# This is function call 
is_loyal "sarthak"
